service_info:
    mode: release
    log_path: ./log/obs.log
    log_level: debug
    storage_path: /obs/
list:
    mysql:
        type: mysql
        user: root
        password: "1234567"
        host: 192.168.31.62
        port: 3307
        database: obs
        charset: utf8
        debug: true
    mongo:
        user: root
        password: "123456"
        host: 192.168.31.62
        port: 27017
        database: log
