service_information:
  port: 8150
  mode: debug
  log: log/obs.log
  version: v1.0.0
  save_root_path: /obs/file/
connection:
  mongo:
    log:
      user: root
      pass: 123456
      host: 192.168.31.62
      port: 27017
      database: log
