service_info:
    port: 8150
    mode: debug
    log_path: ./log/obs.log
    log_level: debug
    storage_path: /obs/
list:
    mysql:
        user: root
        password: "123456"
        host: 192.168.31.62
        port: 3306
        database: obs
        charset: utf8
    mongo:
        user: root
        pass_word: "123456"
        host: 192.168.31.62
        port: 27017
        database: log
