mode: debug
port: 8120
system-log-path: mongodb://admin:1234567@192.168.31.62:27017
system-log_level: debug
storage_path: /obs/
list:
  mysql:
    type: mysql
    user: root
    password: "1234567"
    host: 192.168.31.62
    port: 3307
    database: obs
    charset: utf8
