service_info:
    mode: debug
    #log_path: mongodb://admin:1234567@192.168.31.62:27017
    log_path: ./log/obs.log
    log_level: debug
    storage_path: /obs/
list:
    mysql:
        type: mysql
        user: root
        password: "1234567"
        host: 192.168.31.62
        port: 3307
        database: obs
        charset: utf8
        debug: true
