definitions:
  bucket.Info:
    properties:
      count:
        type: integer
      last_modified:
        type: string
      name:
        type: string
      size:
        type: integer
    type: object
  file.Name:
    properties:
      bucket_name:
        type: string
    required:
    - bucket_name
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a obs server.
  title: obs Swagger API
  version: "1.0"
paths:
  /v1/bucket:
    post:
      consumes:
      - application/json
      description: create bucket
      parameters:
      - description: bucket name
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/file.Name'
      produces:
      - application/json
      responses:
        "201":
          description: bucket_id
          schema:
            type: int
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: CreateBucket
      tags:
      - bucket
  /v1/bucket/{bucket_id}:
    delete:
      consumes:
      - application/json
      description: delete bucket
      parameters:
      - description: bucket id
        in: path
        name: bucket_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: DeleteBucket
      tags:
      - bucket
    head:
      consumes:
      - application/json
      description: head bucket
      parameters:
      - description: bucket id
        in: path
        name: bucket_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: bucket info
          schema:
            $ref: '#/definitions/bucket.Info'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: HeadBucket
      tags:
      - bucket
  /v1/bucket/{bucket_id}/file:
    post:
      consumes:
      - multipart/form-data
      description: upload file
      parameters:
      - description: bucket name
        in: path
        name: bucket_id
        required: true
        type: integer
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: file id
          schema:
            type: int
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: UploadFile
      tags:
      - file
  /v1/bucket/{bucket_id}/file/{file_id}:
    delete:
      consumes:
      - application/json
      description: delete file
      parameters:
      - description: bucket id
        in: path
        name: bucket_id
        required: true
        type: integer
      - description: file id
        in: path
        name: file_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: DeleteFile
      tags:
      - file
    get:
      consumes:
      - application/json
      description: download File
      parameters:
      - description: bucket id
        in: path
        name: bucket_id
        required: true
        type: integer
      - description: file id
        in: path
        name: file_id
        required: true
        type: integer
      - description: sign
        in: query
        name: sign
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: DownloadFile
      tags:
      - file
    head:
      consumes:
      - application/json
      description: head file sign info
      parameters:
      - description: bucket id
        in: path
        name: bucket_id
        required: true
        type: integer
      - description: file id
        in: query
        name: file_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: file link
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: SignFile
      tags:
      - file
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    type: apiKey
swagger: "2.0"
