definitions:
  cpts.Person:
    properties:
      age:
        type: integer
      name:
        type: string
      score:
        type: number
    type: object
  cpts.QueryRequest:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  model.AkSk:
    properties:
      ak:
        type: string
      sk:
        type: string
    required:
    - ak
    - sk
    type: object
  model.BucketName:
    properties:
      bucket_name:
        type: string
    required:
    - bucket_name
    type: object
  model.CreateBucket:
    properties:
      action:
        type: integer
      bucket_name:
        type: string
    required:
    - bucket_name
    type: object
  model.FileInfo:
    properties:
      ak:
        type: string
      bucket_name:
        type: string
      file:
        type: string
      sk:
        type: string
      target:
        type: string
    required:
    - ak
    - bucket_name
    - file
    - sk
    - target
    type: object
  model.SimpleBucket:
    properties:
      ak:
        type: string
      bucket_name:
        type: string
      sk:
        type: string
    required:
    - ak
    - bucket_name
    - sk
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a obs server.
  license: {}
  title: obs Swagger API
  version: "1.0"
paths:
  /test/all:
    post:
      consumes:
      - application/octet-stream
      description: 返回请求数据
      parameters:
      - description: 数据流
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400": {}
        "500": {}
      summary: 返回请求数据
      tags:
      - CPTS
  /test/person:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 上传人物信息
      parameters:
      - description: 任务信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cpts.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cpts.Person'
        "400": {}
        "500": {}
      summary: 上传人物信息
      tags:
      - CPTS
  /test/query:
    get:
      consumes:
      - application/json
      description: 请求参数编码
      parameters:
      - description: 名字
        in: query
        name: name
        type: string
      - description: 年龄
        in: query
        name: age
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cpts.QueryRequest'
        "400": {}
        "500": {}
      summary: 请求参数处理
      tags:
      - CPTS
  /v1/bucket:
    delete:
      consumes:
      - application/json
      description: delete bucket
      parameters:
      - description: bucket
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SimpleBucket'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: DeleteBucket
      tags:
      - bucket
    head:
      consumes:
      - application/json
      description: head bucket
      parameters:
      - description: bucket
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.BucketName'
      produces:
      - application/json
      responses:
        "200":
          headers:
            Last-Modified:
              description: last modify
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: HeadBucket
      tags:
      - bucket
    post:
      consumes:
      - application/json
      description: create bucket
      parameters:
      - description: bucket
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateBucket'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AkSk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: CreateBucket
      tags:
      - bucket
  /v1/file:
    post:
      consumes:
      - multipart/form-data
      description: upload file
      parameters:
      - description: file
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.FileInfo'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "403": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: UploadFile
      tags:
      - file
swagger: "2.0"
