definitions:
  bucket.Info:
    properties:
      count:
        type: integer
      last_modified:
        type: string
      name:
        type: string
      size:
        type: integer
    type: object
  e.ErrorResponse:
    properties:
      code:
        type: string
      extra:
        type: string
      message:
        type: string
    type: object
  file.Name:
    properties:
      bucket_name:
        type: string
    required:
    - bucket_name
    type: object
  user.Domain:
    properties:
      email:
        type: string
      nick:
        type: string
      pass_word:
        type: string
    required:
    - email
    - nick
    - pass_word
    type: object
  user.LoginInfo:
    properties:
      email:
        type: string
      pass_word:
        type: string
    required:
    - email
    - pass_word
    type: object
  user.ModifyInfo:
    properties:
      email:
        type: string
      new_pass_word:
        type: string
      nick:
        type: string
      old_pass_word:
        type: string
    required:
    - email
    type: object
host: http://localhost:8150
info:
  contact: {}
  description: This is a obs server.
  title: obs Swagger API
  version: "1.0"
paths:
  /v1/bucket:
    post:
      consumes:
      - application/json
      description: create bucket
      parameters:
      - description: bucket name
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/file.Name'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: CreateBucket
      tags:
      - bucket
  /v1/bucket/{bucket_name}:
    delete:
      consumes:
      - application/json
      description: delete bucket
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: DeleteBucket
      tags:
      - bucket
    get:
      consumes:
      - application/json
      description: get bucket
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: bucket info
          schema:
            $ref: '#/definitions/bucket.Info'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetBucket
      tags:
      - bucket
  /v1/bucket/{bucket_name}/file:
    post:
      consumes:
      - multipart/form-data
      description: upload file
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: UploadFile
      tags:
      - file
  /v1/bucket/{bucket_name}/file/{file_name}:
    delete:
      consumes:
      - application/json
      description: delete file
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      - description: file name
        in: path
        name: file_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: DeleteFile
      tags:
      - file
    get:
      consumes:
      - application/json
      description: download File
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      - description: file name
        in: path
        name: file_name
        required: true
        type: string
      - description: sign
        in: query
        name: sign
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: DownloadFile
      tags:
      - file
  /v1/bucket/{bucket_name}/file/{file_name}/sign:
    get:
      consumes:
      - application/json
      description: get file sign info
      parameters:
      - description: bucket name
        in: path
        name: bucket_name
        required: true
        type: string
      - description: file name
        in: path
        name: file_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: file link
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: SignFile
      tags:
      - file
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: login request's content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.LoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: Login
      tags:
      - user
  /v1/user/modify:
    put:
      consumes:
      - application/json
      description: user modify
      parameters:
      - description: request's content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ModifyInfo'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "304":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: Modify
      tags:
      - user
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: register request's content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.Domain'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: register
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    type: apiKey
swagger: "2.0"
