definitions:
  bucket.BucketAkSk:
    properties:
      ak:
        type: string
      sk:
        type: string
    type: object
  bucket.CreateRequest:
    properties:
      action:
        type: integer
      bucket_name:
        type: string
    required:
    - bucket_name
    type: object
  cpts.Person:
    properties:
      age:
        type: integer
      name:
        type: string
      score:
        type: number
    type: object
  cpts.QueryRequest:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a obs server.
  license: {}
  title: obs Swagger API
  version: "1.0"
paths:
  /test/all:
    post:
      consumes:
      - application/octet-stream
      description: 返回请求数据
      parameters:
      - description: 数据流
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/octet-stream
      responses:
        "200": {}
        "400": {}
        "500": {}
      summary: 返回请求数据
      tags:
      - CPTS
  /test/person:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 上传人物信息
      parameters:
      - description: 任务信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cpts.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cpts.Person'
        "400": {}
        "500": {}
      summary: 上传人物信息
      tags:
      - CPTS
  /test/query:
    get:
      consumes:
      - application/json
      description: 请求参数编码
      parameters:
      - description: 名字
        in: query
        name: name
        type: string
      - description: 年龄
        in: query
        name: age
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cpts.QueryRequest'
        "400": {}
        "500": {}
      summary: 请求参数处理
      tags:
      - CPTS
  /v1/bucket:
    post:
      consumes:
      - application/json
      description: create bucket
      parameters:
      - description: bucket
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/bucket.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bucket.BucketAkSk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: CreateBucket
      tags:
      - bucket
swagger: "2.0"
